apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cloud-mesh
  name: cloud-mesh
spec:
  replicas: 256 # number of pods to run
  selector:
    matchLabels:
      run: cloud-mesh
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cloud-mesh # metadata label attached to pod
    spec:
      containers:
        - image: bdpedigo/cloud-mesh:v66 # image to pull from dockerhub
          name: cloud-mesh # name of container in pod
          imagePullPolicy: Always
          command: ["/bin/sh"]
          # runners/predict_synapse_compartments_2024-11-07.py
          args: ["-c", "while true; do uv run runners/cloud_morphology_features.py; done"]
          # args: ["-c", "while true; do uv run runners/prediction_on_synapses.py; done"]
          env:
            - name: CLOUDSDK_CORE_PROJECT
              value: ${CLOUDSDK_CORE_PROJECT}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/root/.cloudvolume/secrets/google-secret.json" #TODO
            - name: VERBOSE
              value: "false"
            - name: N_JOBS
              value: "1"
            - name: OPENBLAS_NUM_THREADS
              value: "1"
            - name: MKL_NUM_THREADS
              value: "1"
            - name: NUMEXPR_NUM_THREADS
              value: "1"
            - name: OMP_NUM_THREADS
              value: "1"
            - name: QUEUE_NAME
              value: "ben-skedit"
            - name: RUN
              value: "true"
            - name: LOGGING_LEVEL
              value: "INFO"
            - name: LEASE_SECONDS
              value: "1000"
            - name: RECOMPUTE
              value: "false"
            - name: LINK_PROB
              value: "0.005"

          resources:
            requests:
              memory: 4.0Gi # normal run at 2
              cpu: "900m"
              ephemeral-storage: "4Gi"
            limits:
              memory: "32.0Gi" # normal run at 24
              ephemeral-storage: "16Gi"
          volumeMounts:
            - name: secrets-volume
              mountPath: /root/.cloudvolume/secrets
      dnsPolicy: Default
      volumes:
        - name: secrets-volume
          secret:
            secretName: secrets